backend = "glx";
vsync = true;
use-damage = true;
xrender-sync-fence = true;

shadow = false;
fading = false;
blur-method = "dual_kawase";
blur-strength = 6;
blur-background = true;
blur-background-frame = false;
blur-background-fixed = true;
blur-background-exclude = [
  "class_g != 'Alacritty' && class_g != 'Polybar' && class_g != 'polybar'"
];

corner-radius = 10;
detect-rounded-corners = true;
rounded-corners-exclude = [
  "class_g = 'Polybar'",
  "class_g = 'polybar'"
];
detect-client-opacity = true;
unredir-if-possible = true;
unredir-if-possible-delay = 0;
unredir-if-possible-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'Polybar'",
  "class_g = 'polybar'"
];

frame-opacity = 1.0;
inactive-opacity = 1.0;
active-opacity = 1.0;
