backend = "glx";
vsync = true;
use-damage = true;
xrender-sync-fence = true;

shadow = false;
fading = false;

blur-method = "dual_kawase";
blur-strength = 6;
blur-background = true;
blur-background-exclude = [
  "class_g != 'Polybar' && class_g != 'polybar' && class_g != 'st-256color'"
];

corner-radius = 0;
detect-rounded-corners = true;

detect-client-opacity = true;
unredir-if-possible = true;

opacity-rule = [
  "85:class_g = 'st-256color'"
];
