backend = "glx";
vsync = true;
use-damage = true;
xrender-sync-fence = true;

shadow = false;
fading = false;



corner-radius = 0;
detect-rounded-corners = true;

detect-client-opacity = true;
unredir-if-possible = true;


